# Site settings
title: Антон Фрешер
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://tonyfresher.github.io"
baseurl: "/blog"
permalink: /:categories/:title

# Build settings
markdown: kramdown
sass:
  sass_dir: _css
  style: :compressed
