title: Антон Фрешер
repository: tonyfresher/blog
permalink: /:categories/:title

collections:
  books:
    output: true
    permalink: /:title

markdown: kramdown
sass:
  sass_dir: _css
  style: :compressed
